---
title: "AVES_report"
author: "Lluís Revilla Sancho"
date: "October 24, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load data

Load data from the different reports

```{r}
# model 2 without interaction
model2 <- readRDS("model2_sgcca.RDS")
model2_loo <- readRDS("loo-model2.RDS")

model2_best <- readRDS("model2_best.RDS")
model2_best_loo <- readRDS("loo-model2_best.RDS")

model3 <- readRDS("model3_sgcca.RDS")
model3_loo <- readRDS("loo-model3.RDS")

model3_best <- readRDS("model3_best.RDS")
model3_best_loo <- readRDS("loo-model3_interaction_best.RDS")

superblock <- readRDS("superblock_sgcca.RDS")
superblock_loo <- readRDS("loo-superblock.RDS")

superblock_best <- readRDS("superblock_best.RDS")
superblock_best_loo <- readRDS("loo-superblock_best.RDS")
```


# Evaluate and compare the models

Prepare functions to measure them 

```{r cars}

getAVEs <- function(x, pos = 1L) { 
  x$AVE$AVE_inner[pos]
}

sem <- function(x){
  sd(x)/length(x)
}

m_sem <- function(model, loo) {
  aves <- vapply(loo, getAVEs, numeric(1L))
  paste0(signif(model$AVE$AVE_inner[1], 3), 
        " (", signif(mean(aves), 3),
        " \u00b1 ", scales::scientific(sem(aves), 3), ")")
}
```

# Report values

Model, and mean of the LOO procedure and the SEM:

```{r report}
m_sem(model2, model2_loo) 
m_sem(model2_best, model2_best_loo)
m_sem(model3, model3_loo) 
m_sem(model3_best, model3_best_loo)
m_sem(superblock, superblock_loo)
m_sem(superblock_best, superblock_best_loo)
```

# Plots

We can compare the models. First a helper function:

```{r}
library("dplyr")
library("tidyr")
library("ggplot2")
tidyer <- function(data, model, type) {
  d <- as.data.frame(data) %>% 
    mutate(Model = model) %>% 
    gather(Component, !!type, comp1)
  d$Rownames <- rownames(data)
  if ("comp2" %in% colnames(d)){
    d[, -grep("comp2", colnames(d))]
  } else {
    d
  }
} 

# Prepare some data
data(ge_cgh_locIGR, package = "gliomaData")
data("clinic", package = "gliomaData")
A <- ge_cgh_locIGR$multiblocks
Loc <- factor(ge_cgh_locIGR$y)
levels(Loc) <- colnames(ge_cgh_locIGR$multiblocks$y)

clinic$age_an <- as.numeric(sub(",", ".", as.character(clinic$age_an), fixed = TRUE))
# An outlier of age that we assume that that those are days and not years, 
# so it is divided by 365
clinic$age_an[clinic$age_an > 100] <- clinic$age_an[clinic$age_an > 100]/365.25
meta <- cbind.data.frame(Loc, Age = clinic$age_an, Sex = clinic$sexe)
```
Now we can clean
```{r}
m2GE <- tidyer(model2$Y[[1]], "2", "GE")
m2M <- tidyer(model2$Y[[2]], "2", "CGH")
m2bGE <- tidyer(model2_best$Y[[1]], "2 best", "GE")
m2bM <- tidyer(model2_best$Y[[2]], "2 best", "CGH")
m3GE <- tidyer(model3$Y[[1]], "3", "GE")
m3M <- tidyer(model3$Y[[2]], "3", "CGH")
m3bGE <- tidyer(model3_best$Y[[1]], "3 best", "GE")
m3bM <- tidyer(model3_best$Y[[2]], "3 best", "CGH")
mSGE <- tidyer(superblock$Y[[1]], "superblock", "GE")
mSM <- tidyer(superblock$Y[[2]], "superblock", "CGH")
mSbGE <- tidyer(superblock_best$Y[[1]], "superblock best", "GE")
mSbM <- tidyer(superblock_best$Y[[2]], "superblock best", "CGH")
```

```{r}
df <- rbind(
  merge(m2M, m2GE),
  merge(m2bM, m2bGE),
  merge(m3M, m3GE),
  merge(m3bM, m3bGE),
  merge(mSM, mSGE),
  merge(mSbM, mSbGE)
)
df <- cbind(df, meta)
df <- as_tibble(df)
```

```{r}
df %>% 
  filter(Component == "comp1") %>% 
  ggplot() +
  geom_point(aes(GE, CGH, col = as.factor(Loc))) +
  facet_wrap(~Model, scales = "free") + 
  labs(title = "Samples by model", 
       subtitle = "Colored by localization",
       caption = "Glioma dataset", 
       col = "Localization") + 
  theme_grey() %+replace% 
  theme(panel.background = element_rect(fill = "white", colour = NA), 
        panel.border = element_rect(fill = NA, colour = "grey20"), 
        panel.grid = element_line(colour = "grey92"),
        panel.grid.minor = element_line(size = rel(0.5)),
        strip.background = element_blank(), 
        legend.key = element_rect(fill = "white", colour = NA), 
        complete = TRUE
  ) 
```

